FROM ubuntu:bionic-20200903
RUN apt-get update && apt-get upgrade -y
RUN apt-get install gnupg2 -y

RUN sh -c 'echo "deb http://packages.ros.org/ros/ubuntu bionic main" > /etc/apt/sources.list.d/ros-latest.list'

RUN apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive TZ=UTC apt-get install ros-kinetic-ros-base
RUN apt-get autoremove -y